package database

import (
	"os"
	"testing"

	"university-service/models"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func TestLoadCrawledSnapshot_PopulatesRealData(t *testing.T) {
	dbFile := "test_snapshot_load.db"
	os.Remove(dbFile)
	t.Cleanup(func() { os.Remove(dbFile) })

	db, err := gorm.Open(sqlite.Open(dbFile), &gorm.Config{})
	if err != nil {
		t.Fatalf("failed to open test db: %v", err)
	}
	if err := db.AutoMigrate(&models.University{}, &models.Program{}, &models.Scholarship{}); err != nil {
		t.Fatalf("failed to migrate: %v", err)
	}
	DB = db

	LoadCrawledSnapshot()

	var uniCount, programCount, scholarshipCount int64
	DB.Model(&models.University{}).Count(&uniCount)
	DB.Model(&models.Program{}).Count(&programCount)
	DB.Model(&models.Scholarship{}).Count(&scholarshipCount)

	// Loose lower bounds, not exact numbers — the embedded snapshot can be
	// regenerated by a future crawl run with a slightly different count.
	// The point is confirming the embed+load pipeline actually works, not
	// pinning today's exact figures into a test that breaks on refresh.
	if uniCount < 15 {
		t.Errorf("university count = %d, want at least 15 from the embedded snapshot", uniCount)
	}
	if programCount < 100 {
		t.Errorf("program count = %d, want at least 100 from the embedded snapshot", programCount)
	}
	if scholarshipCount < 20 {
		t.Errorf("scholarship count = %d, want at least 20 from the embedded snapshot", scholarshipCount)
	}
	t.Logf("Loaded from embedded snapshot: %d universities, %d programs, %d scholarships", uniCount, programCount, scholarshipCount)
}

func TestLoadCrawledSnapshot_IdempotentOnSecondRun(t *testing.T) {
	dbFile := "test_snapshot_idempotent.db"
	os.Remove(dbFile)
	t.Cleanup(func() { os.Remove(dbFile) })

	db, err := gorm.Open(sqlite.Open(dbFile), &gorm.Config{})
	if err != nil {
		t.Fatalf("failed to open test db: %v", err)
	}
	if err := db.AutoMigrate(&models.University{}, &models.Program{}, &models.Scholarship{}); err != nil {
		t.Fatalf("failed to migrate: %v", err)
	}
	DB = db

	LoadCrawledSnapshot()
	var firstCount int64
	DB.Model(&models.Program{}).Count(&firstCount)

	LoadCrawledSnapshot() // simulates a second boot against the same DB
	var secondCount int64
	DB.Model(&models.Program{}).Count(&secondCount)

	if firstCount != secondCount {
		t.Errorf("program count changed from %d to %d after reloading the same snapshot -- OnConflict DoNothing should make this idempotent", firstCount, secondCount)
	}
}
