package updater

import (
	"encoding/json"
	"log"
	"os"
)

type OfficialSource struct {
	Name     string   `json:"name"`
	Country  string   `json:"country"`
	Website  string   `json:"website"`
	SeedURLs []string `json:"seed_urls"`
	Kind     string   `json:"kind"`
}

func DefaultOfficialSources() []OfficialSource {
	return []OfficialSource{
		{
			Name:     "Massachusetts Institute of Technology (MIT)",
			Country:  "United States",
			Website:  "https://www.mit.edu",
			Kind:     "graduate_and_undergraduate",
			SeedURLs: []string{"https://oge.mit.edu/graduate-admissions/programs/", "https://www.mit.edu/admissions-aid/"},
		},
		{
			Name:     "Harvard University",
			Country:  "United States",
			Website:  "https://www.harvard.edu",
			Kind:     "program_catalog",
			SeedURLs: []string{"https://www.harvard.edu/programs/", "https://college.harvard.edu/admissions/apply"},
		},
		{
			Name:     "Stanford University",
			Country:  "United States",
			Website:  "https://gradadmissions.stanford.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gradadmissions.stanford.edu/explore-programs"},
		},
		{
			Name:     "University of California, Berkeley",
			Country:  "United States",
			Website:  "https://www.berkeley.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://grad.berkeley.edu/academics/degree-programs/"},
		},
		{
			Name:     "Carnegie Mellon University (CMU)",
			Country:  "United States",
			Website:  "https://www.cmu.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.cmu.edu/academics/programs/index.html"},
		},
		{
			Name:     "University of Oxford",
			Country:  "United Kingdom",
			Website:  "https://www.ox.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.ox.ac.uk/admissions/graduate/courses"},
		},
		{
			Name:     "University of Cambridge",
			Country:  "United Kingdom",
			Website:  "https://www.cam.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.postgraduate.study.cam.ac.uk/courses"},
		},
		{
			Name:     "Imperial College London",
			Country:  "United Kingdom",
			Website:  "https://www.imperial.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.imperial.ac.uk/study/pg/"},
		},
		{
			Name:     "ETH Zurich",
			Country:  "Switzerland",
			Website:  "https://ethz.ch",
			Kind:     "master_degree",
			SeedURLs: []string{"https://ethz.ch/en/studies/master.html"},
		},
		{
			Name:     "Technical University of Munich (TUM)",
			Country:  "Germany",
			Website:  "https://www.tum.de",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.tum.de/en/studies/degree-programs"},
		},
		{
			Name:     "National University of Singapore (NUS)",
			Country:  "Singapore",
			Website:  "https://nus.edu.sg",
			Kind:     "undergraduate_programs",
			SeedURLs: []string{"https://nus.edu.sg/oam/undergraduate-programmes"},
		},
		{
			Name:     "Nanyang Technological University (NTU)",
			Country:  "Singapore",
			Website:  "https://www.ntu.edu.sg",
			Kind:     "graduate_programmes",
			SeedURLs: []string{"https://www.ntu.edu.sg/admissions/graduate"},
		},
		{
			Name:     "University of Tokyo",
			Country:  "Japan",
			Website:  "https://www.u-tokyo.ac.jp",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.u-tokyo.ac.jp/en/academics/degree_programs.html"},
		},
		{
			Name:     "Kyoto University",
			Country:  "Japan",
			Website:  "https://www.kyoto-u.ac.jp",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.kyoto-u.ac.jp/en/education-campus/education-and-admissions"},
		},
		{
			Name:     "University of Melbourne",
			Country:  "Australia",
			Website:  "https://www.unimelb.edu.au",
			Kind:     "courses",
			SeedURLs: []string{"https://study.unimelb.edu.au/find/"},
		},
		{
			Name:     "University of Sydney",
			Country:  "Australia",
			Website:  "https://www.sydney.edu.au",
			Kind:     "courses",
			SeedURLs: []string{"https://www.sydney.edu.au/study/courses.html"},
		},
		{
			Name:     "Monash University",
			Country:  "Australia",
			Website:  "https://www.monash.edu",
			Kind:     "courses",
			SeedURLs: []string{"https://www.monash.edu/study/courses"},
		},
		{
			Name:     "University of Toronto",
			Country:  "Canada",
			Website:  "https://www.utoronto.ca",
			Kind:     "programs",
			SeedURLs: []string{"https://future.utoronto.ca/academics/undergraduate-programs/"},
		},
		{
			Name:     "University of British Columbia (UBC)",
			Country:  "Canada",
			Website:  "https://www.ubc.ca",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.grad.ubc.ca/prospective-students/graduate-degree-programs"},
		},
		{
			Name:     "VinUniversity",
			Country:  "Vietnam",
			Website:  "https://vinuni.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://vinuni.edu.vn/admission/"},
		},
		{
			Name:     "Vietnam National University (VNU)",
			Country:  "Vietnam",
			Website:  "https://vnu.edu.vn",
			Kind:     "admissions",
			SeedURLs: []string{"https://vnu.edu.vn/eng/?C2462"},
		},
		{
			Name:     "Princeton University",
			Country:  "United States",
			Website:  "https://www.princeton.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gradschool.princeton.edu/academics/degrees-departments"},
		},
		{
			Name:     "Yale University",
			Country:  "United States",
			Website:  "https://www.yale.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gsas.yale.edu/academics/departments-programs"},
		},
		{
			Name:     "Columbia University",
			Country:  "United States",
			Website:  "https://www.columbia.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.columbia.edu/content/academics.html"},
		},
		{
			Name:     "University of Pennsylvania",
			Country:  "United States",
			Website:  "https://www.upenn.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.upenn.edu/academics/graduate-professional-schools"},
		},
		{
			Name:     "Cornell University",
			Country:  "United States",
			Website:  "https://www.cornell.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gradschool.cornell.edu/academics/fields-of-study/"},
		},
		{
			Name:     "University of Chicago",
			Country:  "United States",
			Website:  "https://www.uchicago.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.uchicago.edu/en/academics/graduate"},
		},
		{
			Name:     "Duke University",
			Country:  "United States",
			Website:  "https://duke.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gradschool.duke.edu/academics/programs-degrees"},
		},
		{
			Name:     "Northwestern University",
			Country:  "United States",
			Website:  "https://www.northwestern.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.tgs.northwestern.edu/admission/degree-programs/"},
		},
		{
			Name:     "Johns Hopkins University",
			Country:  "United States",
			Website:  "https://www.jhu.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.jhu.edu/academics/graduate-programs/"},
		},
		{
			Name:     "University of Michigan",
			Country:  "United States",
			Website:  "https://umich.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://rackham.umich.edu/programs/"},
		},
		{
			Name:     "University of California, Los Angeles (UCLA)",
			Country:  "United States",
			Website:  "https://www.ucla.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://grad.ucla.edu/programs/"},
		},
		{
			Name:     "New York University (NYU)",
			Country:  "United States",
			Website:  "https://www.nyu.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.nyu.edu/admissions/graduate-admissions/explore-nyu-graduate-programs.html"},
		},
		{
			Name:     "University of Washington",
			Country:  "United States",
			Website:  "https://www.washington.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.grad.uw.edu/programs-of-study/"},
		},
		{
			Name:     "Georgia Institute of Technology",
			Country:  "United States",
			Website:  "https://www.gatech.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://grad.gatech.edu/degree-programs"},
		},
		{
			Name:     "University of Illinois Urbana-Champaign",
			Country:  "United States",
			Website:  "https://illinois.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://grad.illinois.edu/programs"},
		},
		{
			Name:     "University College London (UCL)",
			Country:  "United Kingdom",
			Website:  "https://www.ucl.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.ucl.ac.uk/prospective-students/graduate"},
		},
		{
			Name:     "University of Edinburgh",
			Country:  "United Kingdom",
			Website:  "https://www.ed.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.ed.ac.uk/studying/postgraduate"},
		},
		{
			Name:     "King's College London",
			Country:  "United Kingdom",
			Website:  "https://www.kcl.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.kcl.ac.uk/study/postgraduate"},
		},
		{
			Name:     "London School of Economics (LSE)",
			Country:  "United Kingdom",
			Website:  "https://www.lse.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.lse.ac.uk/study-at-lse/Graduate"},
		},
		{
			Name:     "University of Manchester",
			Country:  "United Kingdom",
			Website:  "https://www.manchester.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.manchester.ac.uk/study/masters/"},
		},
		{
			Name:     "University of Bristol",
			Country:  "United Kingdom",
			Website:  "https://www.bristol.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.bristol.ac.uk/study/postgraduate/"},
		},
		{
			Name:     "University of Warwick",
			Country:  "United Kingdom",
			Website:  "https://warwick.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://warwick.ac.uk/study/postgraduate/"},
		},
		{
			Name:     "École Polytechnique Fédérale de Lausanne (EPFL)",
			Country:  "Switzerland",
			Website:  "https://www.epfl.ch",
			Kind:     "master_degree",
			SeedURLs: []string{"https://www.epfl.ch/education/master/"},
		},
		{
			Name:     "University of Zurich",
			Country:  "Switzerland",
			Website:  "https://www.uzh.ch",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uzh.ch/en/studies/programs.html"},
		},
		{
			Name:     "Ludwig Maximilian University of Munich (LMU)",
			Country:  "Germany",
			Website:  "https://www.lmu.de",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.lmu.de/en/study/all-degree-programs/index.html"},
		},
		{
			Name:     "Heidelberg University",
			Country:  "Germany",
			Website:  "https://www.uni-heidelberg.de",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uni-heidelberg.de/en/study/all-degree-programs"},
		},
		{
			Name:     "RWTH Aachen University",
			Country:  "Germany",
			Website:  "https://www.rwth-aachen.de",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/studiengaenge/~qax/liste-studiengaenge/"},
		},
		{
			Name:     "Delft University of Technology (TU Delft)",
			Country:  "Netherlands",
			Website:  "https://www.tudelft.nl",
			Kind:     "master_degree",
			SeedURLs: []string{"https://www.tudelft.nl/en/education/programmes/masters"},
		},
		{
			Name:     "University of Amsterdam",
			Country:  "Netherlands",
			Website:  "https://www.uva.nl",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uva.nl/en/programmes/masters/masters.html"},
		},
		{
			Name:     "Sorbonne University",
			Country:  "France",
			Website:  "https://www.sorbonne-universite.fr",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.sorbonne-universite.fr/en/education/course-catalogue"},
		},
		{
			Name:     "Sciences Po",
			Country:  "France",
			Website:  "https://www.sciencespo.fr",
			Kind:     "master_degree",
			SeedURLs: []string{"https://www.sciencespo.fr/admissions/en/masters-admissions.html"},
		},
		{
			Name:     "KTH Royal Institute of Technology",
			Country:  "Sweden",
			Website:  "https://www.kth.se",
			Kind:     "master_degree",
			SeedURLs: []string{"https://www.kth.se/en/studies/master"},
		},
		{
			Name:     "University of Copenhagen",
			Country:  "Denmark",
			Website:  "https://www.ku.dk",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://studies.ku.dk/masters/"},
		},
		{
			Name:     "Peking University",
			Country:  "China",
			Website:  "https://www.pku.edu.cn",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://admission.pku.edu.cn/"},
		},
		{
			Name:     "Tsinghua University",
			Country:  "China",
			Website:  "https://www.tsinghua.edu.cn",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.tsinghua.edu.cn/en/Admissions.htm"},
		},
		{
			Name:     "Fudan University",
			Country:  "China",
			Website:  "https://www.fudan.edu.cn",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.fdso.fudan.edu.cn/"},
		},
		{
			Name:     "University of Hong Kong (HKU)",
			Country:  "Hong Kong",
			Website:  "https://www.hku.hk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.aal.hku.hk/tpg/programmes"},
		},
		{
			Name:     "Chinese University of Hong Kong (CUHK)",
			Country:  "Hong Kong",
			Website:  "https://www.cuhk.edu.hk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.gs.cuhk.edu.hk/prospective-students/programs"},
		},
		{
			Name:     "Hong Kong University of Science and Technology (HKUST)",
			Country:  "Hong Kong",
			Website:  "https://hkust.edu.hk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://join.hkust.edu.hk/programs"},
		},
		{
			Name:     "Seoul National University",
			Country:  "South Korea",
			Website:  "https://www.snu.ac.kr",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://admission.snu.ac.kr/graduate"},
		},
		{
			Name:     "Korea Advanced Institute of Science and Technology (KAIST)",
			Country:  "South Korea",
			Website:  "https://www.kaist.ac.kr",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://admission.kaist.ac.kr/graduate/"},
		},
		{
			Name:     "Yonsei University",
			Country:  "South Korea",
			Website:  "https://www.yonsei.ac.kr",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://admission.yonsei.ac.kr/en/grad/"},
		},
		{
			Name:     "Osaka University",
			Country:  "Japan",
			Website:  "https://www.osaka-u.ac.jp",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.osaka-u.ac.jp/en/education"},
		},
		{
			Name:     "Tokyo Institute of Technology",
			Country:  "Japan",
			Website:  "https://www.titech.ac.jp",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.titech.ac.jp/english/graduate_school"},
		},
		{
			Name:     "National Taiwan University",
			Country:  "Taiwan",
			Website:  "https://www.ntu.edu.tw",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://oga.ntu.edu.tw/en/admission-2/"},
		},
		{
			Name:     "University of Malaya",
			Country:  "Malaysia",
			Website:  "https://www.um.edu.my",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://ipsforms.um.edu.my/"},
		},
		{
			Name:     "Chulalongkorn University",
			Country:  "Thailand",
			Website:  "https://www.chula.ac.th",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.grad.chula.ac.th/"},
		},
		{
			Name:     "Australian National University (ANU)",
			Country:  "Australia",
			Website:  "https://www.anu.edu.au",
			Kind:     "courses",
			SeedURLs: []string{"https://www.anu.edu.au/study/study-options"},
		},
		{
			Name:     "University of Queensland",
			Country:  "Australia",
			Website:  "https://www.uq.edu.au",
			Kind:     "courses",
			SeedURLs: []string{"https://www.uq.edu.au/study/"},
		},
		{
			Name:     "University of New South Wales (UNSW)",
			Country:  "Australia",
			Website:  "https://www.unsw.edu.au",
			Kind:     "courses",
			SeedURLs: []string{"https://www.unsw.edu.au/study"},
		},
		{
			Name:     "McGill University",
			Country:  "Canada",
			Website:  "https://www.mcgill.ca",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.mcgill.ca/gradapplicants/programs"},
		},
		{
			Name:     "University of Waterloo",
			Country:  "Canada",
			Website:  "https://uwaterloo.ca",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://uwaterloo.ca/graduate-studies-academic-calendar/"},
		},
		{
			Name:     "University of Alberta",
			Country:  "Canada",
			Website:  "https://www.ualberta.ca",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.ualberta.ca/en/graduate-studies/programs/index.html"},
		},
		{
			Name:     "University of Auckland",
			Country:  "New Zealand",
			Website:  "https://www.auckland.ac.nz",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.auckland.ac.nz/en/study.html"},
		},
		{
			Name:     "Trinity College Dublin",
			Country:  "Ireland",
			Website:  "https://www.tcd.ie",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.tcd.ie/courses/postgraduate/"},
		},
		{
			Name:     "University College Dublin (UCD)",
			Country:  "Ireland",
			Website:  "https://www.ucd.ie",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.ucd.ie/graduatestudies/programmesa-z/"},
		},
		{
			Name:     "Ho Chi Minh City University of Technology (HCMUT)",
			Country:  "Vietnam",
			Website:  "https://hcmut.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://tuyensinh.hcmut.edu.vn/"},
		},
		{
			Name:     "University of Economics Ho Chi Minh City (UEH)",
			Country:  "Vietnam",
			Website:  "https://www.ueh.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://tuyensinh.ueh.edu.vn/"},
		},
		{
			Name:     "Hanoi University of Science and Technology (HUST)",
			Country:  "Vietnam",
			Website:  "https://hust.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://ts.hust.edu.vn/"},
		},
		{
			Name:     "Foreign Trade University (FTU)",
			Country:  "Vietnam",
			Website:  "https://ftu.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://tuyensinh.ftu.edu.vn/"},
		},
		{
			Name:     "RMIT University Vietnam",
			Country:  "Vietnam",
			Website:  "https://www.rmit.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://www.rmit.edu.vn/study-with-us"},
		},
		{
			Name:     "Fulbright University Vietnam",
			Country:  "Vietnam",
			Website:  "https://fulbright.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://fulbright.edu.vn/admissions/"},
		},
	}
}

func LoadOfficialSources() []OfficialSource {
	raw := os.Getenv("UNIVERSITY_OFFICIAL_SOURCES_JSON")
	if raw == "" {
		return DefaultOfficialSources()
	}

	var sources []OfficialSource
	if err := json.Unmarshal([]byte(raw), &sources); err != nil {
		log.Printf("[Updater] Invalid UNIVERSITY_OFFICIAL_SOURCES_JSON, falling back to defaults: %v", err)
		return DefaultOfficialSources()
	}

	return sources
}
