package updater

import (
	"encoding/json"
	"log"
	"os"
)

type OfficialSource struct {
	Name     string   `json:"name"`
	Country  string   `json:"country"`
	Website  string   `json:"website"`
	SeedURLs []string `json:"seed_urls"`
	Kind     string   `json:"kind"`
}

func DefaultOfficialSources() []OfficialSource {
	return []OfficialSource{
		{
			Name:     "Massachusetts Institute of Technology (MIT)",
			Country:  "United States",
			Website:  "https://www.mit.edu",
			Kind:     "graduate_and_undergraduate",
			SeedURLs: []string{"https://oge.mit.edu/graduate-admissions/programs/", "https://www.mit.edu/admissions-aid/"},
		},
		{
			Name:     "Harvard University",
			Country:  "United States",
			Website:  "https://www.harvard.edu",
			Kind:     "program_catalog",
			SeedURLs: []string{"https://www.harvard.edu/programs/", "https://college.harvard.edu/admissions/apply"},
		},
		{
			Name:     "Stanford University",
			Country:  "United States",
			Website:  "https://gradadmissions.stanford.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gradadmissions.stanford.edu/explore-programs"},
		},
		{
			Name:     "University of California, Berkeley",
			Country:  "United States",
			Website:  "https://www.berkeley.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://grad.berkeley.edu/academics/degree-programs/"},
		},
		{
			Name:     "Carnegie Mellon University (CMU)",
			Country:  "United States",
			Website:  "https://www.cmu.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.cmu.edu/academics/programs/index.html"},
		},
		{
			Name:     "University of Oxford",
			Country:  "United Kingdom",
			Website:  "https://www.ox.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.ox.ac.uk/admissions/graduate/courses"},
		},
		{
			Name:     "University of Cambridge",
			Country:  "United Kingdom",
			Website:  "https://www.cam.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.postgraduate.study.cam.ac.uk/courses"},
		},
		{
			Name:     "Imperial College London",
			Country:  "United Kingdom",
			Website:  "https://www.imperial.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.imperial.ac.uk/study/pg/"},
		},
		{
			Name:     "ETH Zurich",
			Country:  "Switzerland",
			Website:  "https://ethz.ch",
			Kind:     "master_degree",
			SeedURLs: []string{"https://ethz.ch/en/studies/master.html"},
		},
		{
			Name:     "Technical University of Munich (TUM)",
			Country:  "Germany",
			Website:  "https://www.tum.de",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.tum.de/en/studies/degree-programs"},
		},
		{
			Name:     "National University of Singapore (NUS)",
			Country:  "Singapore",
			Website:  "https://nus.edu.sg",
			Kind:     "undergraduate_programs",
			SeedURLs: []string{"https://nus.edu.sg/oam/undergraduate-programmes"},
		},
		{
			Name:     "Nanyang Technological University (NTU)",
			Country:  "Singapore",
			Website:  "https://www.ntu.edu.sg",
			Kind:     "graduate_programmes",
			SeedURLs: []string{"https://www.ntu.edu.sg/admissions/graduate"},
		},
		{
			Name:     "University of Tokyo",
			Country:  "Japan",
			Website:  "https://www.u-tokyo.ac.jp",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.u-tokyo.ac.jp/en/academics/degree_programs.html"},
		},
		{
			Name:     "Kyoto University",
			Country:  "Japan",
			Website:  "https://www.kyoto-u.ac.jp",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.kyoto-u.ac.jp/en/education-campus/education-and-admissions"},
		},
		{
			Name:     "University of Melbourne",
			Country:  "Australia",
			Website:  "https://www.unimelb.edu.au",
			Kind:     "courses",
			SeedURLs: []string{"https://study.unimelb.edu.au/find/"},
		},
		{
			Name:     "University of Sydney",
			Country:  "Australia",
			Website:  "https://www.sydney.edu.au",
			Kind:     "courses",
			SeedURLs: []string{"https://www.sydney.edu.au/study/courses.html"},
		},
		{
			Name:     "Monash University",
			Country:  "Australia",
			Website:  "https://www.monash.edu",
			Kind:     "courses",
			SeedURLs: []string{"https://www.monash.edu/study/courses"},
		},
		{
			Name:     "University of Toronto",
			Country:  "Canada",
			Website:  "https://www.utoronto.ca",
			Kind:     "programs",
			SeedURLs: []string{"https://future.utoronto.ca/academics/undergraduate-programs/"},
		},
		{
			Name:     "University of British Columbia (UBC)",
			Country:  "Canada",
			Website:  "https://www.ubc.ca",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.grad.ubc.ca/prospective-students/graduate-degree-programs"},
		},
		{
			Name:     "VinUniversity",
			Country:  "Vietnam",
			Website:  "https://vinuni.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://vinuni.edu.vn/admission/"},
		},
		{
			Name:     "Vietnam National University (VNU)",
			Country:  "Vietnam",
			Website:  "https://vnu.edu.vn",
			Kind:     "admissions",
			SeedURLs: []string{"https://vnu.edu.vn/eng/?C2462"},
		},
		{
			Name:     "Princeton University",
			Country:  "United States",
			Website:  "https://www.princeton.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gradschool.princeton.edu/academics/degrees-departments"},
		},
		{
			Name:     "Yale University",
			Country:  "United States",
			Website:  "https://www.yale.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gsas.yale.edu/academics/departments-programs"},
		},
		{
			Name:     "Columbia University",
			Country:  "United States",
			Website:  "https://www.columbia.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.columbia.edu/content/academics.html"},
		},
		{
			Name:     "University of Pennsylvania",
			Country:  "United States",
			Website:  "https://www.upenn.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.upenn.edu/academics/graduate-professional-schools"},
		},
		{
			Name:     "Cornell University",
			Country:  "United States",
			Website:  "https://www.cornell.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gradschool.cornell.edu/academics/fields-of-study/"},
		},
		{
			Name:     "University of Chicago",
			Country:  "United States",
			Website:  "https://www.uchicago.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.uchicago.edu/en/academics/graduate"},
		},
		{
			Name:     "Duke University",
			Country:  "United States",
			Website:  "https://duke.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gradschool.duke.edu/academics/programs-degrees"},
		},
		{
			Name:     "Northwestern University",
			Country:  "United States",
			Website:  "https://www.northwestern.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.tgs.northwestern.edu/admission/degree-programs/"},
		},
		{
			Name:     "Johns Hopkins University",
			Country:  "United States",
			Website:  "https://www.jhu.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.jhu.edu/academics/graduate-programs/"},
		},
		{
			Name:     "University of Michigan",
			Country:  "United States",
			Website:  "https://umich.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://rackham.umich.edu/programs/"},
		},
		{
			Name:     "University of California, Los Angeles (UCLA)",
			Country:  "United States",
			Website:  "https://www.ucla.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://grad.ucla.edu/programs/"},
		},
		{
			Name:     "New York University (NYU)",
			Country:  "United States",
			Website:  "https://www.nyu.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.nyu.edu/admissions/graduate-admissions/explore-nyu-graduate-programs.html"},
		},
		{
			Name:     "University of Washington",
			Country:  "United States",
			Website:  "https://www.washington.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.grad.uw.edu/programs-of-study/"},
		},
		{
			Name:     "Georgia Institute of Technology",
			Country:  "United States",
			Website:  "https://www.gatech.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://grad.gatech.edu/degree-programs"},
		},
		{
			Name:     "University of Illinois Urbana-Champaign",
			Country:  "United States",
			Website:  "https://illinois.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://grad.illinois.edu/programs"},
		},
		{
			Name:     "University College London (UCL)",
			Country:  "United Kingdom",
			Website:  "https://www.ucl.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.ucl.ac.uk/prospective-students/graduate"},
		},
		{
			Name:     "University of Edinburgh",
			Country:  "United Kingdom",
			Website:  "https://www.ed.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.ed.ac.uk/studying/postgraduate"},
		},
		{
			Name:     "King's College London",
			Country:  "United Kingdom",
			Website:  "https://www.kcl.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.kcl.ac.uk/study/postgraduate"},
		},
		{
			Name:     "London School of Economics (LSE)",
			Country:  "United Kingdom",
			Website:  "https://www.lse.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.lse.ac.uk/study-at-lse/Graduate"},
		},
		{
			Name:     "University of Manchester",
			Country:  "United Kingdom",
			Website:  "https://www.manchester.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.manchester.ac.uk/study/masters/"},
		},
		{
			Name:     "University of Bristol",
			Country:  "United Kingdom",
			Website:  "https://www.bristol.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.bristol.ac.uk/study/postgraduate/"},
		},
		{
			Name:     "University of Warwick",
			Country:  "United Kingdom",
			Website:  "https://warwick.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://warwick.ac.uk/study/postgraduate/"},
		},
		{
			Name:     "École Polytechnique Fédérale de Lausanne (EPFL)",
			Country:  "Switzerland",
			Website:  "https://www.epfl.ch",
			Kind:     "master_degree",
			SeedURLs: []string{"https://www.epfl.ch/education/master/"},
		},
		{
			Name:     "University of Zurich",
			Country:  "Switzerland",
			Website:  "https://www.uzh.ch",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uzh.ch/en/studies/programs.html"},
		},
		{
			Name:     "Ludwig Maximilian University of Munich (LMU)",
			Country:  "Germany",
			Website:  "https://www.lmu.de",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.lmu.de/en/study/all-degree-programs/index.html"},
		},
		{
			Name:     "Heidelberg University",
			Country:  "Germany",
			Website:  "https://www.uni-heidelberg.de",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uni-heidelberg.de/en/study/all-degree-programs"},
		},
		{
			Name:     "RWTH Aachen University",
			Country:  "Germany",
			Website:  "https://www.rwth-aachen.de",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/studiengaenge/~qax/liste-studiengaenge/"},
		},
		{
			Name:     "Delft University of Technology (TU Delft)",
			Country:  "Netherlands",
			Website:  "https://www.tudelft.nl",
			Kind:     "master_degree",
			SeedURLs: []string{"https://www.tudelft.nl/en/education/programmes/masters"},
		},
		{
			Name:     "University of Amsterdam",
			Country:  "Netherlands",
			Website:  "https://www.uva.nl",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uva.nl/en/programmes/masters/masters.html"},
		},
		{
			Name:     "Sorbonne University",
			Country:  "France",
			Website:  "https://www.sorbonne-universite.fr",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.sorbonne-universite.fr/en/education/course-catalogue"},
		},
		{
			Name:     "Sciences Po",
			Country:  "France",
			Website:  "https://www.sciencespo.fr",
			Kind:     "master_degree",
			SeedURLs: []string{"https://www.sciencespo.fr/admissions/en/masters-admissions.html"},
		},
		{
			Name:     "KTH Royal Institute of Technology",
			Country:  "Sweden",
			Website:  "https://www.kth.se",
			Kind:     "master_degree",
			SeedURLs: []string{"https://www.kth.se/en/studies/master"},
		},
		{
			Name:     "University of Copenhagen",
			Country:  "Denmark",
			Website:  "https://www.ku.dk",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://studies.ku.dk/masters/"},
		},
		{
			Name:     "Peking University",
			Country:  "China",
			Website:  "https://www.pku.edu.cn",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://admission.pku.edu.cn/"},
		},
		{
			Name:     "Tsinghua University",
			Country:  "China",
			Website:  "https://www.tsinghua.edu.cn",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.tsinghua.edu.cn/en/Admissions.htm"},
		},
		{
			Name:     "Fudan University",
			Country:  "China",
			Website:  "https://www.fudan.edu.cn",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.fdso.fudan.edu.cn/"},
		},
		{
			Name:     "University of Hong Kong (HKU)",
			Country:  "Hong Kong",
			Website:  "https://www.hku.hk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.aal.hku.hk/tpg/programmes"},
		},
		{
			Name:     "Chinese University of Hong Kong (CUHK)",
			Country:  "Hong Kong",
			Website:  "https://www.cuhk.edu.hk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.gs.cuhk.edu.hk/prospective-students/programs"},
		},
		{
			Name:     "Hong Kong University of Science and Technology (HKUST)",
			Country:  "Hong Kong",
			Website:  "https://hkust.edu.hk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://join.hkust.edu.hk/programs"},
		},
		{
			Name:     "Seoul National University",
			Country:  "South Korea",
			Website:  "https://www.snu.ac.kr",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://admission.snu.ac.kr/graduate"},
		},
		{
			Name:     "Korea Advanced Institute of Science and Technology (KAIST)",
			Country:  "South Korea",
			Website:  "https://www.kaist.ac.kr",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://admission.kaist.ac.kr/graduate/"},
		},
		{
			Name:     "Yonsei University",
			Country:  "South Korea",
			Website:  "https://www.yonsei.ac.kr",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://admission.yonsei.ac.kr/en/grad/"},
		},
		{
			Name:     "Osaka University",
			Country:  "Japan",
			Website:  "https://www.osaka-u.ac.jp",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.osaka-u.ac.jp/en/education"},
		},
		{
			Name:     "Tokyo Institute of Technology",
			Country:  "Japan",
			Website:  "https://www.titech.ac.jp",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.titech.ac.jp/english/graduate_school"},
		},
		{
			Name:     "National Taiwan University",
			Country:  "Taiwan",
			Website:  "https://www.ntu.edu.tw",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://oga.ntu.edu.tw/en/admission-2/"},
		},
		{
			Name:     "University of Malaya",
			Country:  "Malaysia",
			Website:  "https://www.um.edu.my",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://ipsforms.um.edu.my/"},
		},
		{
			Name:     "Chulalongkorn University",
			Country:  "Thailand",
			Website:  "https://www.chula.ac.th",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.grad.chula.ac.th/"},
		},
		{
			Name:     "Australian National University (ANU)",
			Country:  "Australia",
			Website:  "https://www.anu.edu.au",
			Kind:     "courses",
			SeedURLs: []string{"https://www.anu.edu.au/study/study-options"},
		},
		{
			Name:     "University of Queensland",
			Country:  "Australia",
			Website:  "https://www.uq.edu.au",
			Kind:     "courses",
			SeedURLs: []string{"https://www.uq.edu.au/study/"},
		},
		{
			Name:     "University of New South Wales (UNSW)",
			Country:  "Australia",
			Website:  "https://www.unsw.edu.au",
			Kind:     "courses",
			SeedURLs: []string{"https://www.unsw.edu.au/study"},
		},
		{
			Name:     "McGill University",
			Country:  "Canada",
			Website:  "https://www.mcgill.ca",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.mcgill.ca/gradapplicants/programs"},
		},
		{
			Name:     "University of Waterloo",
			Country:  "Canada",
			Website:  "https://uwaterloo.ca",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://uwaterloo.ca/graduate-studies-academic-calendar/"},
		},
		{
			Name:     "University of Alberta",
			Country:  "Canada",
			Website:  "https://www.ualberta.ca",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.ualberta.ca/en/graduate-studies/programs/index.html"},
		},
		{
			Name:     "University of Auckland",
			Country:  "New Zealand",
			Website:  "https://www.auckland.ac.nz",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.auckland.ac.nz/en/study.html"},
		},
		{
			Name:     "Trinity College Dublin",
			Country:  "Ireland",
			Website:  "https://www.tcd.ie",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.tcd.ie/courses/postgraduate/"},
		},
		{
			Name:     "University College Dublin (UCD)",
			Country:  "Ireland",
			Website:  "https://www.ucd.ie",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.ucd.ie/graduatestudies/programmesa-z/"},
		},
		{
			Name:     "California Institute of Technology (Caltech)",
			Country:  "United States",
			Website:  "https://www.caltech.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.gradoffice.caltech.edu/programs"},
		},
		{
			Name:     "University of Texas at Austin",
			Country:  "United States",
			Website:  "https://www.utexas.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gradschool.utexas.edu/academics/graduate-degree-programs"},
		},
		{
			Name:     "Purdue University",
			Country:  "United States",
			Website:  "https://www.purdue.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.purdue.edu/gradschool/prospective/programs/"},
		},
		{
			Name:     "University of Wisconsin-Madison",
			Country:  "United States",
			Website:  "https://www.wisc.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://grad.wisc.edu/programs/"},
		},
		{
			Name:     "University of Southern California (USC)",
			Country:  "United States",
			Website:  "https://www.usc.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://graduateschool.usc.edu/programs/"},
		},
		{
			Name:     "Boston University",
			Country:  "United States",
			Website:  "https://www.bu.edu",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.bu.edu/academics/degree-level/graduate/"},
		},
		{
			Name:     "Queen's University",
			Country:  "Canada",
			Website:  "https://www.queensu.ca",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.queensu.ca/sgs/programs"},
		},
		{
			Name:     "McMaster University",
			Country:  "Canada",
			Website:  "https://www.mcmaster.ca",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://gs.mcmaster.ca/programs/"},
		},
		{
			Name:     "Bocconi University",
			Country:  "Italy",
			Website:  "https://www.unibocconi.it",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.unibocconi.eu/wps/wcm/connect/bocconi/sitopubblico_en/navigation+tree/home/programs"},
		},
		{
			Name:     "Politecnico di Milano",
			Country:  "Italy",
			Website:  "https://www.polimi.it",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.polimi.it/en/education/all-programmes"},
		},
		{
			Name:     "University of Barcelona",
			Country:  "Spain",
			Website:  "https://www.ub.edu",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.ub.edu/en/web/en/estudis/oferta_formativa/masters_universitaris/"},
		},
		{
			Name:     "IE University",
			Country:  "Spain",
			Website:  "https://www.ie.edu",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.ie.edu/university/studies/"},
		},
		{
			Name:     "University of Vienna",
			Country:  "Austria",
			Website:  "https://www.univie.ac.at",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.univie.ac.at/en/studies/degree-programmes/"},
		},
		{
			Name:     "Aalto University",
			Country:  "Finland",
			Website:  "https://www.aalto.fi",
			Kind:     "master_degree",
			SeedURLs: []string{"https://www.aalto.fi/en/study-options/aalto-university-masters-programmes"},
		},
		{
			Name:     "University of Helsinki",
			Country:  "Finland",
			Website:  "https://www.helsinki.fi",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.helsinki.fi/en/admissions/degree-programmes"},
		},
		{
			Name:     "Indian Institute of Technology Bombay (IIT Bombay)",
			Country:  "India",
			Website:  "https://www.iitb.ac.in",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.iitb.ac.in/en/education/academic-programmes"},
		},
		{
			Name:     "Indian Institute of Technology Delhi (IIT Delhi)",
			Country:  "India",
			Website:  "https://home.iitd.ac.in",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://home.iitd.ac.in/academic-programs.php"},
		},
		{
			Name:     "Waseda University",
			Country:  "Japan",
			Website:  "https://www.waseda.jp",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.waseda.jp/top/en/academics/graduate-schools"},
		},
		{
			Name:     "Keio University",
			Country:  "Japan",
			Website:  "https://www.keio.ac.jp",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.keio.ac.jp/en/academics/graduate-schools/"},
		},
		{
			Name:     "King Abdullah University of Science and Technology (KAUST)",
			Country:  "Saudi Arabia",
			Website:  "https://www.kaust.edu.sa",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://www.kaust.edu.sa/en/study/programs"},
		},
		{
			Name:     "New York University Abu Dhabi",
			Country:  "United Arab Emirates",
			Website:  "https://nyuad.nyu.edu",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://nyuad.nyu.edu/en/academics/majors-and-minors.html"},
		},
		{
			Name:     "University of Cape Town",
			Country:  "South Africa",
			Website:  "https://www.uct.ac.za",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uct.ac.za/main/study-uct/postgraduate/prospective-programmes-brochure"},
		},
		{
			Name:     "University of the Witwatersrand",
			Country:  "South Africa",
			Website:  "https://www.wits.ac.za",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.wits.ac.za/study-at-wits/postgraduate/"},
		},
		{
			Name:     "Universidad Nacional Autónoma de México (UNAM)",
			Country:  "Mexico",
			Website:  "https://www.unam.mx",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.unam.mx/oferta-educativa"},
		},
		{
			Name:     "University of São Paulo (USP)",
			Country:  "Brazil",
			Website:  "https://www5.usp.br",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www5.usp.br/english/graduate-programs/"},
		},
		{
			Name:     "Pontificia Universidad Católica de Chile",
			Country:  "Chile",
			Website:  "https://www.uc.cl",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uc.cl/en/academics"},
		},
		{
			Name:     "University of Ottawa",
			Country:  "Canada",
			Website:  "https://www.uottawa.ca",
			Kind:     "graduate_programs",
			SeedURLs: []string{"https://catalogue.uottawa.ca/en/graduate/"},
		},
		{
			Name:     "University of St Andrews",
			Country:  "United Kingdom",
			Website:  "https://www.st-andrews.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.st-andrews.ac.uk/subjects/postgraduate/"},
		},
		{
			Name:     "Durham University",
			Country:  "United Kingdom",
			Website:  "https://www.durham.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://www.durham.ac.uk/study/postgraduate/"},
		},
		{
			Name:     "University of Leeds",
			Country:  "United Kingdom",
			Website:  "https://www.leeds.ac.uk",
			Kind:     "postgraduate_courses",
			SeedURLs: []string{"https://courses.leeds.ac.uk/postgraduate"},
		},
		{
			Name:     "University of Groningen",
			Country:  "Netherlands",
			Website:  "https://www.rug.nl",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.rug.nl/masters/"},
		},
		{
			Name:     "Utrecht University",
			Country:  "Netherlands",
			Website:  "https://www.uu.nl",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uu.nl/en/masters"},
		},
		{
			Name:     "Ghent University",
			Country:  "Belgium",
			Website:  "https://www.ugent.be",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.ugent.be/en/study/programmes"},
		},
		{
			Name:     "KU Leuven",
			Country:  "Belgium",
			Website:  "https://www.kuleuven.be",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.kuleuven.be/english/education/programmes"},
		},
		{
			Name:     "University of Warsaw",
			Country:  "Poland",
			Website:  "https://www.uw.edu.pl",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://irk.uw.edu.pl/en/"},
		},
		{
			Name:     "University of Oslo",
			Country:  "Norway",
			Website:  "https://www.uio.no",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uio.no/english/studies/masters/"},
		},
		{
			Name:     "Norwegian University of Science and Technology (NTNU)",
			Country:  "Norway",
			Website:  "https://www.ntnu.edu",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.ntnu.edu/studies/mastersprogrammes"},
		},
		{
			Name:     "Hebrew University of Jerusalem",
			Country:  "Israel",
			Website:  "https://www.huji.ac.il",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://en.huji.ac.il/schools-and-programs"},
		},
		{
			Name:     "Technion – Israel Institute of Technology",
			Country:  "Israel",
			Website:  "https://www.technion.ac.il",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.technion.ac.il/en/academic-programs/"},
		},
		{
			Name:     "Indian Institute of Science (IISc)",
			Country:  "India",
			Website:  "https://www.iisc.ac.in",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.iisc.ac.in/academics/academic-programs/"},
		},
		{
			Name:     "Indian Institute of Technology Madras (IIT Madras)",
			Country:  "India",
			Website:  "https://www.iitm.ac.in",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.iitm.ac.in/academic-programmes"},
		},
		{
			Name:     "Fudan University Graduate School",
			Country:  "China",
			Website:  "https://www.fudan.edu.cn",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://gsao.fudan.edu.cn/"},
		},
		{
			Name:     "Zhejiang University",
			Country:  "China",
			Website:  "https://www.zju.edu.cn",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.zju.edu.cn/english/2019/0716/c30274a1972475/page.htm"},
		},
		{
			Name:     "Universiti Teknologi Malaysia (UTM)",
			Country:  "Malaysia",
			Website:  "https://www.utm.my",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.utm.my/study-at-utm/"},
		},
		{
			Name:     "University of the Philippines",
			Country:  "Philippines",
			Website:  "https://up.edu.ph",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://up.edu.ph/academics/"},
		},
		{
			Name:     "Universitas Indonesia",
			Country:  "Indonesia",
			Website:  "https://www.ui.ac.id",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://admission.ui.ac.id/"},
		},
		{
			Name:     "University of Ghana",
			Country:  "Ghana",
			Website:  "https://www.ug.edu.gh",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.ug.edu.gh/admissions/"},
		},
		{
			Name:     "American University in Cairo",
			Country:  "Egypt",
			Website:  "https://www.aucegypt.edu",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.aucegypt.edu/academics/programs"},
		},
		{
			Name:     "University of Buenos Aires",
			Country:  "Argentina",
			Website:  "https://www.uba.ar",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uba.ar/estudiantes/oferta-academica/"},
		},
		{
			Name:     "Universidad de los Andes",
			Country:  "Colombia",
			Website:  "https://uniandes.edu.co",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://uniandes.edu.co/en/academics"},
		},
		{
			Name:     "Lund University",
			Country:  "Sweden",
			Website:  "https://www.lu.se",
			Kind:     "master_degree",
			SeedURLs: []string{"https://www.lu.se/en/education/masters-programmes"},
		},
		{
			Name:     "Uppsala University",
			Country:  "Sweden",
			Website:  "https://www.uu.se",
			Kind:     "degree_programs",
			SeedURLs: []string{"https://www.uu.se/en/study/masters"},
		},
		{
			Name:     "Ho Chi Minh City University of Technology (HCMUT)",
			Country:  "Vietnam",
			Website:  "https://hcmut.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://tuyensinh.hcmut.edu.vn/"},
		},
		{
			Name:     "University of Economics Ho Chi Minh City (UEH)",
			Country:  "Vietnam",
			Website:  "https://www.ueh.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://tuyensinh.ueh.edu.vn/"},
		},
		{
			Name:     "Hanoi University of Science and Technology (HUST)",
			Country:  "Vietnam",
			Website:  "https://hust.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://ts.hust.edu.vn/"},
		},
		{
			Name:     "Foreign Trade University (FTU)",
			Country:  "Vietnam",
			Website:  "https://ftu.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://tuyensinh.ftu.edu.vn/"},
		},
		{
			Name:     "RMIT University Vietnam",
			Country:  "Vietnam",
			Website:  "https://www.rmit.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://www.rmit.edu.vn/study-with-us"},
		},
		{
			Name:     "Fulbright University Vietnam",
			Country:  "Vietnam",
			Website:  "https://fulbright.edu.vn",
			Kind:     "academic_programs",
			SeedURLs: []string{"https://fulbright.edu.vn/admissions/"},
		},
	}
}

func LoadOfficialSources() []OfficialSource {
	raw := os.Getenv("UNIVERSITY_OFFICIAL_SOURCES_JSON")
	if raw == "" {
		return DefaultOfficialSources()
	}

	var sources []OfficialSource
	if err := json.Unmarshal([]byte(raw), &sources); err != nil {
		log.Printf("[Updater] Invalid UNIVERSITY_OFFICIAL_SOURCES_JSON, falling back to defaults: %v", err)
		return DefaultOfficialSources()
	}

	return sources
}
